import type { Metadata } from 'next';
import './globals.css';
import { ThemeProvider } from 'next-themes';
import { NextAuthProvider } from '~/components/layout/auth-provider';
import { SWRProvider } from '~/components/layout/swr-provider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link
          href="https://fonts.googleapis.com/css2?family=Geist:wght@100..900&display=swap"
          rel="stylesheet"
        />
      </head>

      <body>
        <ThemeProvider attribute="class" defaultTheme="light" enableSystem disableTransitionOnChange>
          <NextAuthProvider>
            <SWRProvider>
              <div className="min-h-screen bg-background">{children}</div>
            </SWRProvider>
          </NextAuthProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
