import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { ThemeProvider } from 'next-themes';
import { NextAuthProvider } from '~/components/layout/auth-provider';
import { SWRProvider } from '~/components/layout/swr-provider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <ThemeProvider attribute="class" defaultTheme="light" enableSystem disableTransitionOnChange>
          <NextAuthProvider>
            <SWRProvider>
              <div className="min-h-screen bg-background">{children}</div>
            </SWRProvider>
          </NextAuthProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
